openapi: 3.1.0
info:
  title: Complaints API
  version: 1.0.0
  description: API for managing complaints within a system
servers: 
  - url: /api/v1
paths:
  /complaints:
    get:
      summary: List complaints
      description: Get a list of all complaints in the system
      tags:
        - Complaints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Complaint'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    post:
      summary: Create Complaint
      description: Create a new complaint in the system.
      tags:
        - Complaints
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/ComplaintCreate'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Complaint'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity (e.g. validation errors)
        '500':
          description: Internal Server Error
  /complaints/{id}:
    get:
      summary: Get a complaint item
      description: Get details of a specific complaint by its ID.
      tags:
        - Complaints
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Complaint'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    put:
      summary: Update Complaint
      description: Update an existing complaint
      tags:
        - Complaints
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComplaintUpdate'
      responses:
        '200':
          description: OK
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/Complaint'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '422':
          description: Unprocessable Entity (e.g. validation errors)
        '500':
          description: Internal Server Error
components:
  schemas:
    Complaint:
      type: object
      properties:
        id: 
          type: string
          format: uuid
          description: Unique identifier for the complaint
        subject:
          type: string
          description: Subject of the complaint
        description:
          type: string
          description: Detailed description of the complaint
        category:
          type: string
          description: Category of the complaint (e.g. Billing, Service)
        status:
          type: string
          description: Current status of the complaint
          enum:
            - Open
            - In Progress
            - Resolved
            - Cancelled
    ComplaintCreate:
      type: object
      required:
        - subject
        - description
        - category
      properties:
        subject:
          type: string
          description: Subject of the complaint
        description:
          type: string
          description: Detailed description of the complaint
        category:
          type: string
          description: Category of the complaint (e.g. Billing, Service)
    ComplaintUpdate:
      type: object
      properties:
        subject:
          type: string
          description: Subject of the complaint
        description:
          type: string
          description: Detailed description of the complaint
        category:
          type: string
          description: Category of the complaint (e.g. Billing, Service)
        status:
          type: string
          description: Current status of the complaint
          enum:
            - Open
            - In Progress
            - Resolved
            - Cancelled
